<div class="row">
	<!-- Widget ID (each widget will need unique ID)-->
	<div class="jarviswidget jarviswidget-color-darken" data-widget-editbutton="false" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-collapsed="false">
		<header>
			<span class="widget-icon"> <i class="fa fa-table"></i> </span>
			<h2>Finance Analysis</h2>
		</header>
		<!-- widget div-->
		<div>
			<!-- widget edit box -->
			<div class="jarviswidget-editbox">
				<!-- This area used as dropdown edit box -->
			</div>
			<!-- end widget edit box -->
			<!-- widget content -->
			<?php 
			$count_sport = count($sport);
			?>
			<div class="widget-body no-padding">
				<table id="reportTable" class="table table-striped table-bordered table-hover" width="100%">
					<thead>
						<tr>
							<th></th>
							<th colspan="3">Sites</th>
							<th colspan="3" style="border-left: solid 1px black">Sector</th>
						</tr>
						<tr>
							<th data-class="expand">Sport</th>
							<th>Average Booking £</th>
							<th>Average Secondary £</th>
							<th>Average Total</th>
							<th>Average Booking £</th>
							<th>Average Secondary £</th>
							<th>Average Total</th>
							
						</tr>
					</thead>

					<tbody>
						<?php 
						for ($i = 0; $i < $count_sport; $i++)
						{
							$sport_name = $SportTableSports->find($sport[$i])->name;
							if(!isset($sport_name))
							{
								$sport_name = "Other";
							}
							?>
							<tr style="cursor: pointer;" onclick='displayResult("<?php echo $sport[$i]; ?>","<?php echo $sport_name; ?>")'>
								<td><?php echo $sport_name; ?></td>
								<?php
								
								//sites
								$cost = $site_co[$sport[$i]];
								$sp_amount = $site_sp[$sport[$i]];

								if ($demo) 
								{
									$cost *= (rand(7, 14)) / 10;
									$sp_amount *= (rand(7, 14)) / 10;
								}

								?>
								<td align="right"><?php echo number_format($cost,2); ?></td>
								<td align="right"><?php echo number_format($sp_amount,2); ?></td>
								<td align="right"><?php echo number_format($cost + $sp_amount,2); ?></td>
								<?php 

								//sector
								$cost = $all_co[$sport[$i]];
								$sp_amount = $all_sp[$sport[$i]];

								if ($demo) 
								{
									$cost *= (rand(7, 14)) / 10;
									$sp_amount *= (rand(7, 14)) / 10;
								}

								?>
								<td align="right"><?php echo number_format($cost,2); ?></td>
								<td align="right"><?php echo number_format($sp_amount,2); ?></td>
								<td align="right"><?php echo number_format($cost + $sp_amount,2); ?></td>
								<?php
							}

							?>
						</tbody>
					</table>
				</div>
				<!-- end widget content -->
			</div>
			<!-- end widget div -->
		</div>
		<!-- end widget -->
	</div>
	<script type="text/javascript">

		$('body').delegate('#reportTable tbody tr', "click", function () {
			if(!$(this).hasClass('row-detail'))
			{
				$(this).addClass('highlight_c').siblings().removeClass('highlight_c');
			} 				
		});

		function displayResult(sport, sport_name)
		{
			$.ajax({
				url: '{{ route("activity-barometer.postGraphFinance") }}',
				type: 'POST',
				data: {
					sport:      		sport,
					sport_name: 		sport_name,
					start_date: 		'<?php echo $date_start_parsed ?>',
					end_date:        	'<?php echo $date_end_parsed ?>',
					sites:  			'<?php echo json_encode($sites); ?>'
				},
				success: function(data) 
				{
					$('#graph').show().html(data);
					$.smallBox({
						title : "Success",
						content : "<i class='fa fa-clock-o'></i> <i>The graph has been successfully generated!</i>",
						color : "#659265",
						iconSmall : "fa fa-check fa-2x fadeInRight animated",
						timeout : 3000
					});
				}
			});
		}

		/* BASIC ;*/
		var responsiveHelper_reportTable = undefined;
		var breakpointDefinition = {
			tablet : 1024,
			phone : 480
		};

		/* TABLETOOLS */
		$('#reportTable').dataTable({

			// Tabletools options: 
			//   https://datatables.net/extensions/tabletools/button_options
			"sDom": "<'dt-toolbar'<'col-xs-12 col-sm-7'lf><'col-sm-5 col-xs-6 hidden-xs'T>r>"+
			"t"+
			"<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
			"oTableTools": {
				"aButtons" : ["copy", {
					"sExtends": "print",
					"sMessage": "Generated by 4Global <i>(press Esc to close)</i>"
				}, {
					"sExtends" : "collection",
					"sButtonText" : 'Save <span class="caret" />',
					"aButtons" : ["csv", "xls", {
						"sExtends": "pdf",
						"sPdfMessage": "Generated by 4Global",
						"sPdfSize": "letter"
					}]
				}],
				"sSwfPath": "<?php echo URL::asset('js/plugin/datatables/swf/copy_csv_xls_pdf.swf') ?>"
			},
			"autoWidth" : true,
			"preDrawCallback" : function() {
				// Initialize the responsive datatables helper once.
				if (!responsiveHelper_reportTable) {
					responsiveHelper_reportTable = new ResponsiveDatatablesHelper($('#reportTable'), breakpointDefinition);
				}
			},
			"rowCallback" : function(nRow) {
				responsiveHelper_reportTable.createExpandIcon(nRow);
			},
			"drawCallback" : function(oSettings) {
				responsiveHelper_reportTable.respond();
			}
		});
</script>
@include('templates.widget')